### ISSUE TITLE
The theme doesn't seem to want to work in the library. 

### ISSUE THREAD

**Issue by Beacroxx** [Dukeatron/steam#18]
![2023-03-26-23-24-50-Screenshot](https://user-images.githubusercontent.com/80547533/227805499-580c9268-0b49-44cd-833d-7849bfbfc69e.png)  
It works everywhere else, just the library is scuffed.  
I am on Wayland (if that matters). I also tried both automatic (somehow i got bugged theme with that one) and manual.

**Comment by TheBearodactyl** [comment]
sorry about the bug in the automated script, I currently have a fix for that waiting to be merged lol

**Comment by TheBearodactyl** [comment]
sorry about the bug in the automated script, I currently have a fix for that waiting to be merged lol. also, to fix the black bar on the bottom, just press on any game in your library, it'll go away then

**Comment by TheBearodactyl** [comment]
> ![2023-03-26-23-24-50-Screenshot](https://user-images.githubusercontent.com/80547533/227805499-580c9268-0b49-44cd-833d-7849bfbfc69e.png)  
> It works everywhere else, just the library is scuffed.  
> I am on Wayland (if that matters). I also tried both automatic (somehow i got bugged theme with that one) and manual.

also, i see you are a fellow Puro appreciator

**Comment by TheBearodactyl** [comment]
> ![2023-03-26-23-24-50-Screenshot](https://user-images.githubusercontent.com/80547533/227805499-580c9268-0b49-44cd-833d-7849bfbfc69e.png) It works everywhere else, just the library is scuffed. I am on Wayland (if that matters). I also tried both automatic (somehow i got bugged theme with that one) and manual.

The automated script is fixed

**Comment by Oman395** [comment]
Library is broken currently on the latest steam version-- as far as I can tell, I can't style the library with webkit.css, and the theme we are working off for the library also doesn't work, so honestly I'm just going to wait until it's patched.

**Comment by tamsyn548** [comment]
still not working
![image](https://user-images.githubusercontent.com/111175305/229337890-85de44ab-5db7-49ad-878a-9ab74abcf7bc.png)


> > ![2023-03-26-23-24-50-Screenshot](https://user-images.githubusercontent.com/80547533/227805499-580c9268-0b49-44cd-833d-7849bfbfc69e.png) It works everywhere else, just the library is scuffed. I am on Wayland (if that matters). I also tried both automatic (somehow i got bugged theme with that one) and manual.
> 
> The automated script is fixed

**Comment by TheBearodactyl** [comment]
> still not working
> ![image](https://user-images.githubusercontent.com/111175305/229337890-85de44ab-5db7-49ad-878a-9ab74abcf7bc.png)
> 
> 
> > > ![2023-03-26-23-24-50-Screenshot](https://user-images.githubusercontent.com/80547533/227805499-580c9268-0b49-44cd-833d-7849bfbfc69e.png) It works everywhere else, just the library is scuffed. I am on Wayland (if that matters). I also tried both automatic (somehow i got bugged theme with that one) and manual.
> > 
> > The automated script is fixed
> 
> 

as I said in a different reply, to fix the little black bar on the bottom, you have to press one of the items in your library. It's a bug with the current steam client, and this is the only solution for now

**Comment by tamsyn548** [comment]
I don't even have a black bar. This is my screenshot

![image](https://user-images.githubusercontent.com/111175305/229341660-a3b8f6d9-d2ee-4f35-8c1d-bcd5b0b6b078.png)

the problem is that the library does not change colors, even though in the screenshots on the main github page, it should

**Comment by TheBearodactyl** [comment]
> I don't even have a black bar. This is my screenshot
> 
> ![image](https://user-images.githubusercontent.com/111175305/229341660-a3b8f6d9-d2ee-4f35-8c1d-bcd5b0b6b078.png)
> 
> the problem is that the library does not change colors, even though in the screenshots on the main github page, it should

as @Oman395 already said:
> Library is broken currently on the latest steam version-- as far as I can tell, I can't style the library with webkit.css, and the theme we are working off for the library also doesn't work, so honestly I'm just going to wait until it's patched.

also, black bar:![Screenshot_20230402-033403.png](https://user-images.githubusercontent.com/114454115/229341801-f49bacd0-c2d9-47f4-89d9-eb0757907c97.png)
